### ISSUE TITLE
warning: [deprecation] getFlutterEngine() in FlutterPluginBinding has been deprecated

### ISSUE THREAD

**Issue by Zrufy** [jerson/flutter-rsa#10]
Hi i have this error when i'm building my app with flutter for android.Have you any solution?

**Comment by jerson** [comment]
Hi @Zrufy thanks, I think it's an alert and I don't know if that will stop me from compiling, but I think it's something that can be corrected, in a few hours when I have free time I will investigate the solution

**Comment by Zrufy** [comment]
Thanks to you for this library it has facilitated me a lot.

**Comment by jerson** [comment]
hi @Zrufy please can you test with latest version 

https://pub.dev/packages/fast_rsa/versions/1.1.4

**Comment by Zrufy** [comment]
I tried to build and it didn't give me any errors for now so thank you. In case I keep you updated. What kind of error was it?

**Comment by jerson** [comment]
was a warning this line about deprecated syntax

https://github.com/jerson/flutter-rsa/blob/master/android/src/main/java/dev/jerson/rsa/RsaPlugin.java#L56


by now i think is ok close this issue but feel free to reopen if you have some additional info
