### ISSUE TITLE
Execution failed for task ':fast_rsa:bundleDebugAar'.

### ISSUE THREAD

**Issue by ares-arman** [jerson/flutter-rsa#11]
Hi. 
I have a problem with installing. 
Can you help ? 

* What went wrong:
Execution failed for task ':fast_rsa:bundleDebugAar'.
> Direct local .aar file dependencies are not supported when building an AAR. The resulting AAR would be broken because the classes and Android resources from any local .aar file dependencies would not be packaged in the resulting AAR. Previous versions of the Android Gradle Plugin produce broken AARs in this case too (despite not throwing this error). The following direct local .aar file dependencies of the :fast_rsa project caused this error: F:\src\flutter\.pub-cache\hosted\pub.dartlang.org\fast_rsa-1.1.4\android\libs\rsa.aar

**Comment by jerson** [comment]
hi @ares-arman thank you for report the issue, please can you try with latest rc version

https://pub.dev/packages/fast_rsa/versions/1.2.0-rc1
