### ISSUE TITLE
decrypting with an invalid private key caused a panic and the app crashed.

### ISSUE THREAD

**Issue by dbviewer-zigen** [jerson/flutter-rsa#13]
Hello 

I am making an application that encrypts and decrypts using fast rsa.
but, decrypting with an invalid private key caused a panic and the app crashed.
I want to handle it as an exception when I specify an invalid private key.

```dart
      KeyPair keyPair = await RSA.generate(2048);
      String plainText = "ABCDEFG";
      var ciphertext = await RSA.encryptPKCS1v15(plainText, keyPair.publicKey);

      // case 1. OK
      var result = await RSA.decryptPKCS1v15(ciphertext, keyPair.privateKey);
      plainText == result ? print("OK") : print("NG");

      // case 2. NG  "panic: runtime error: invalid memory address or nil pointer dereference" was output to the console
      result = await RSA.decryptPKCS1v15(ciphertext, "hogehogehoge");
      plainText == result ? print("OK") : print("NG");
```

enviroment

* Android Studio 3.6.3
* Flutter 1.22.4
* Dart 2.10.4
* fast rsa 1.3.2    (fast_rsa: ^1.3.2)

E/Go      ( 5587): panic: runtime error: invalid memory address or nil pointer dereference
E/Go      ( 5587): [signal SIGSEGV: segmentation violation code=0x1 addr=0xc pc=0xa9eef31a]
E/Go      ( 5587): 
E/Go      ( 5587): goroutine 17 [running, locked to thread]:
E/Go      ( 5587): github.com/jerson/rsa-mobile/rsa.(*FastRSA).readPrivateKey(0x7982ee7b, 0x79816150, 0xc, 0x169, 0x0, 0x0)
E/Go      ( 5587): 	/home/runner/work/rsa-mobile/rsa-mobile/rsa/common.go:17 +0x5a
E/Go      ( 5587): github.com/jerson/rsa-mobile/rsa.(*FastRSA).decryptPKCS1v15(0x7982ee7b, 0x799aab40, 0x100, 0x102, 0x79816150, 0xc, 0x0, 0x0, 0x7989c5e0, 0x0, ...)
E/Go      ( 5587): 	/home/runner/work/rsa-mobile/rsa-mobile/rsa/decrypt_pkcsv15.go:29 +0x36
E/Go      ( 5587): github.com/jerson/rsa-mobile/rsa.(*FastRSA).DecryptPKCS1v15(0x7982ee7b, 0x799802c0, 0x158, 0x79816150, 0xc, 0x0, 0x0, 0x79820000, 0xd3bd96d0)
E/Go      ( 5587): 	/home/runner/work/rsa-mobile/rsa-mobile/rsa/decrypt_pkcsv15.go:15 +0x83
E/Go      ( 5587): github.com/jerson/rsa-mobile/bridge.instance.decryptPKCS1v15(0x7982ee7b, 0x799ac000, 0x169, 0x169, 0x799ac000, 0xe64c9de0)
E/Go      ( 5587): 	/home/runner/work/rsa-mobile/rsa-mobile/bridge/call.go:347 +0x102
E/Go      ( 5587): github.com/jerson/rsa-mobile/bridge.Call(0x79816140, 0xf, 0x799ac000, 0x169, 0x169, 0x1, 0x0, 0xa9f7be60, 0xa9bdbff2, 0x79890030)
E/Go      ( 5587): 	/home/runner/work/rsa-mobile/rsa-mobile/bridge/call.go:43 +0x42b
E/Go      ( 5587): main.RSABridgeCall(0xd3bd96d0, 0xe64c9de0, 0x169, 0x0)
E/Go      ( 5587): 	/home/runner/work/rsa-mobile/rsa-mobile/binding/main.go:17 +0x7b
E/Go      ( 5587): main._cgoexpwrap_0aae0d41709f_RSABridgeCall(0xd3bd96d0, 0xe64c9de0, 0x169, 0x0)
E/Go      ( 5587): 	_cgo_gotypes.go:106 +0x69
F/libc    ( 5587): Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 5908 (DartWorker), pid 5587 (er.app.password)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***

**Comment by jerson** [comment]
hi @dbviewer-zigen thanks for report the issue, have you tried using try catch ? or doesnt work ?

**Comment by dbviewer-zigen** [comment]
hi jerson, 

Unfortunately , The same problem occurs when I used try-catch.

Could you verify it with the code below?

```dart
import 'package:fast_rsa/model/bridge.pb.dart';
import 'package:fast_rsa/rsa.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void rsaTest() async{
    try{
      KeyPair keyPair = await RSA.generate(2048);
      String plainText = "ABCDEFG";
      var ciphertext = await RSA.encryptPKCS1v15(plainText, keyPair.publicKey);
      // case 1. OK
      var result = await RSA.decryptPKCS1v15(ciphertext, keyPair.privateKey);
      plainText == result ? print("OK") : print("NG");
      // case 2. NG  "panic: runtime error: invalid memory address or nil pointer dereference" was output to the console
      result = await RSA.decryptPKCS1v15(ciphertext, "hogehogehoge");
      plainText == result ? print("OK") : print("NG");
      print("succseed.");
    } catch(e, st){
      print(e);
      print(st);
    }

  }

  void _incrementCounter() {
    setState(() {
      print("start-fast-rsa");
      rsaTest();
      print("end-fast-rsa");
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}

```


Launching lib/main.dart on sdk gphone x86 in debug mode...
Running Gradle task 'assembleDebug'...
✓ Built build/app/outputs/flutter-apk/app-debug.apk.
Installing build/app/outputs/flutter-apk/app.apk...
Waiting for sdk gphone x86 to report its views...
Debug service listening on ws://127.0.0.1:51199/R38r8KJGQyg=/ws
Syncing files to device sdk gphone x86...
I/flutter (22572): start-fast-rsa
I/flutter (22572): end-fast-rsa
I/flutter (22572): OK
E/Go      (22572): panic: runtime error: invalid memory address or nil pointer dereference
E/Go      (22572): [signal SIGSEGV: segmentation violation code=0x1 addr=0xc pc=0xadb7331a]
E/Go      (22572): 
E/Go      (22572): goroutine 17 [running, locked to thread]:
E/Go      (22572): github.com/jerson/rsa-mobile/rsa.(*FastRSA).readPrivateKey(0x7d42ee7b, 0x7d416100, 0xc, 0x169, 0x0, 0x0)
E/Go      (22572): 	/home/runner/work/rsa-mobile/rsa-mobile/rsa/common.go:17 +0x5a
E/Go      (22572): github.com/jerson/rsa-mobile/rsa.(*FastRSA).decryptPKCS1v15(0x7d42ee7b, 0x7d8b8c60, 0x100, 0x102, 0x7d416100, 0xc, 0x0, 0x0, 0x7d444220, 0x0, ...)
E/Go      (22572): 	/home/runner/work/rsa-mobile/rsa-mobile/rsa/decrypt_pkcsv15.go:29 +0x36
E/Go      (22572): github.com/jerson/rsa-mobile/rsa.(*FastRSA).DecryptPKCS1v15(0x7d42ee7b, 0x7d8962c0, 0x158, 0x7d416100, 0xc, 0x0, 0x0, 0x7d420000, 0xd3954fb0)
E/Go      (22572): 	/home/runner/work/rsa-mobile/rsa-mobile/rsa/decrypt_pkcsv15.go:15 +0x83
E/Go      (22572): github.com/jerson/rsa-mobile/bridge.instance.decryptPKCS1v15(0x7d42ee7b, 0x7d8ba000, 0x169, 0x169, 0x7d8ba000, 0xe64c6d70)
E/Go      (22572): 	/home/runner/work/rsa-mobile/rsa-mobile/bridge/call.go:347 +0x102
E/Go      (22572): github.com/jerson/rsa-mobile/bridge.Call(0x7d4160f0, 0xf, 0x7d8ba000, 0x169, 0x169, 0x1, 0x0, 0xadbffe60, 0xad85fff2, 0x7d490030)
E/Go      (22572): 	/home/runner/work/rsa-mobile/rsa-mobile/bridge/call.go:43 +0x42b
E/Go      (22572): main.RSABridgeCall(0xd3954fb0, 0xe64c6d70, 0x169, 0x0)
E/Go      (22572): 	/home/runner/work/rsa-mobile/rsa-mobile/binding/main.go:17 +0x7b
E/Go      (22572): main._cgoexpwrap_0aae0d41709f_RSABridgeCall(0xd3954fb0, 0xe64c6d70, 0x169, 0x0)
E/Go      (22572): 	_cgo_gotypes.go:106 +0x69
F/libc    (22572): Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 22670 (DartWorker), pid 22572 (fast_rsa_sample)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'google/sdk_gphone_x86/generic_x86_arm:11/RSR1.200819.001.A1/6823625:user/release-keys'
Revision: '0'
ABI: 'x86'
Timestamp: 2021-02-05 08:04:20+0900
pid: 22572, tid: 22670, name: DartWorker  >>> zigen.flutter.app.fast.flutter_fast_rsa_sample <<<
uid: 10157
signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
    eax 00000000  ebx 0000582c  ecx 0000588e  edx 00000006
    edi 00000000  esi 00000008
    ebp 00000000  esp 7d42ecd8  eip ad8ba400
backtrace:
      #00 pc 000e5400  /data/app/~~fdl9OfgqE7tq4WqoMvvU7w==/zigen.flutter.app.fast.flutter_fast_rsa_sample-jITnf2ieWexx-RdNnrW_XA==/lib/x86/librsa_bridge.so

**Comment by jerson** [comment]
hi @dbviewer-zigen thanks for that, yeah im going to reproduce here i think is related to go so probably will be fixed soon

**Comment by jerson** [comment]
@dbviewer-zigen good news i found the issue and now is fixed, please help me to test and check that now is working

https://pub.dev/packages/fast_rsa/versions/1.3.3

**Comment by dbviewer-zigen** [comment]
@jerson 

I have confirmed that the problem has been resolved.

Thank you for your support!!

**Comment by jerson** [comment]
yeah @dbviewer-zigen we can improve this in the future, probably is only change this line

https://github.com/jerson/flutter-rsa/blob/master/lib/bridge/binding.dart#L85

**Comment by jerson** [comment]
also added custom `RSAException` in https://pub.dev/packages/fast_rsa/versions/1.3.5
