### ISSUE TITLE
Migrate to null safety 

### ISSUE THREAD

**Issue by nilsreichardt** [jerson/flutter-rsa#14]
## Description
I think all dependencies are migrated to null safety. So we can migrate this packages as well.

## Resources
* [How to migrate Dart packages to null safety](https://youtu.be/eBr5tlumwlg)
* [Announcing Dart null safety beta](https://medium.com/dartlang/announcing-dart-null-safety-beta-87610fee6730)

**Comment by jerson** [comment]
hi @nilsreichardt thanks for that, im going to start upgrading this week

**Comment by jerson** [comment]
initial version released: https://pub.dev/packages/fast_rsa/versions/1.4.0-nullsafety.1

there are some deprecations but for now im going to close this ticket, so in the future we can improve support
