### ISSUE TITLE
clang: error: no such file or directory:  .../ios/.symlinks/plugins/fast_rsa/iOS/librsa_bridge.a 

### ISSUE THREAD

**Issue by ZacharieAzoulai** [jerson/flutter-rsa#22]
Hi,

I just updated from version 3.0.0 to version 3.0.2 and when I try to run my app it fails

`Ld /Users/zhack013/Library/Developer/Xcode/DerivedData/Runner-drdfnjevxzlztjhfrpamxswjnzqu/Build/Products/Debug-iphoneos/Runner.app/Runner normal (in target 'Runner' from project 'Runner')
    cd /Users/zhack013/Library/Mobile\ Documents/com\~apple\~CloudDocs/Workspace/Perso/Missions/KISAPP/Code/kisapp/ios
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -target arm64-apple-ios9.0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.5.sdk -L/Users/zhack013/Library/Developer/Xcode/DerivedData/Runner-drdfnjevxzlztjhfrpamxswjnzqu/Build/Products/Debug-iphoneos -L/Users/zhack013/Library/Developer/Xcode/DerivedData/Runner-drdfnjevxzlztjhfrpamxswjnzqu/Build/Products/Debug-iphoneos/device_info -L/Users/zhack013/Library/Developer/Xcode/DerivedData/Runner-drdfnjevxzlztjhfrpamxswjnzqu/Build/Products/Debug-iphoneos/device_info_plus -L/Users/zhack013/Library/Developer/Xcode/DerivedData/Runner-drdfnjevxzlztjhfrpamxswjnzqu/Build/Products/Debug-iphoneos/fast_rsa -L/Users/zhack013/Library/Developer/Xcode/DerivedData/Runner-drdfnjevxzlztjhfrpamxswjnzqu/Build/Products/Debug-iphoneos/flutter_contacts -L/Users/zhack013/Library/Developer/Xcode/DerivedData/Runner-drdfnjevxzlztjhfrpamxswjnzqu/Build/Products/Debug-iphoneos/flutter_keychain -L/Users/zhack013/Library/Developer/Xcode/DerivedData/Runner-drdfnjevxzlztjhfrpamxswjnzqu/Build/Products/Debug-iphoneos/flutter_secure_storage -L/Users/zhack013/Library/Developer/Xcode/DerivedData/Runner-drdfnjevxzlztjhfrpamxswjnzqu/Build/Products/Debug-iphoneos/image_picker -L/Users/zhack013/Library/Developer/Xcode/DerivedData/Runner-drdfnjevxzlztjhfrpamxswjnzqu/Build/Products/Debug-iphoneos/onesignal_flutter -L/Users/zhack013/Library/Developer/Xcode/DerivedData/Runner-drdfnjevxzlztjhfrpamxswjnzqu/Build/Products/Debug-iphoneos/path_provider -L/Users/zhack013/Library/Developer/Xcode/DerivedData/Runner-drdfnjevxzlztjhfrpamxswjnzqu/Build/Products/Debug-iphoneos/record -L/Users/zhack013/Library/Developer/Xcode/DerivedData/Runner-drdfnjevxzlztjhfrpamxswjnzqu/Build/Products/Debug-iphoneos/shared_preferences -L/Users/zhack013/Library/Mobile\ Documents/com\~apple\~CloudDocs/Workspace/Perso/Missions/KISAPP/Code/kisapp/ios/Pods/../.symlinks/plugins/fast_rsa/ios -F/Users/zhack013/Library/Developer/Xcode/DerivedData/Runner-drdfnjevxzlztjhfrpamxswjnzqu/Build/Products/Debug-iphoneos -F/Users/zhack013/Library/Mobile\ Documents/com\~apple\~CloudDocs/Workspace/Perso/Missions/KISAPP/Code/kisapp/ios/Pods/OneSignalXCFramework/iOS_SDK/OneSignalSDK/OneSignal_XCFramework -F/Users/zhack013/Library/Developer/Xcode/DerivedData/Runner-drdfnjevxzlztjhfrpamxswjnzqu/Build/Products/Debug-iphoneos/XCFrameworkIntermediates/OneSignal -filelist /Users/zhack013/Library/Developer/Xcode/DerivedData/Runner-drdfnjevxzlztjhfrpamxswjnzqu/Build/Intermediates.noindex/Runner.build/Debug-iphoneos/Runner.build/Objects-normal/arm64/Runner.LinkFileList -Xlinker -rpath -Xlinker /usr/lib/swift -Xlinker -rpath -Xlinker @executable_path/Frameworks -dead_strip -Xlinker -object_path_lto -Xlinker /Users/zhack013/Library/Developer/Xcode/DerivedData/Runner-drdfnjevxzlztjhfrpamxswjnzqu/Build/Intermediates.noindex/Runner.build/Debug-iphoneos/Runner.build/Objects-normal/arm64/Runner_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate -fobjc-arc -fobjc-link-runtime -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphoneos -L/usr/lib/swift -Xlinker -add_ast_path -Xlinker /Users/zhack013/Library/Developer/Xcode/DerivedData/Runner-drdfnjevxzlztjhfrpamxswjnzqu/Build/Intermediates.noindex/Runner.build/Debug-iphoneos/Runner.build/Objects-normal/arm64/Runner.swiftmodule -ObjC -ldevice_info -ldevice_info_plus -lfast_rsa -lflutter_contacts -lflutter_keychain -lflutter_secure_storage -limage_picker -lonesignal_flutter -lpath_provider -lrecord -lrsa_bridge -lshared_preferences -framework OneSignal -force_load /Users/zhack013/Library/Mobile Documents/com\~apple\~CloudDocs/Workspace/Perso/Missions/KISAPP/Code/kisapp/ios/.symlinks/plugins/fast_rsa/ios/librsa_bridge.a -lPods-Runner -Xlinker -no_adhoc_codesign -Xlinker -dependency_info -Xlinker /Users/zhack013/Library/Developer/Xcode/DerivedData/Runner-drdfnjevxzlztjhfrpamxswjnzqu/Build/Intermediates.noindex/Runner.build/Debug-iphoneos/Runner.build/Objects-normal/arm64/Runner_dependency_info.dat -o /Users/zhack013/Library/Developer/Xcode/DerivedData/Runner-drdfnjevxzlztjhfrpamxswjnzqu/Build/Products/Debug-iphoneos/Runner.app/Runner

clang: error: no such file or directory: 'Documents/com~apple~CloudDocs/Workspace/Perso/Missions/KISAPP/Code/kisapp/ios/.symlinks/plugins/fast_rsa/ios/librsa_bridge.a'
Command Ld failed with a nonzero exit code`

The thing is it says that the path is 'Documents/com~apple~CloudDocs/Workspace/Perso/Missions/KISAPP/Code/kisapp/ios/.symlinks/plugins/fast_rsa/ios/librsa_bridge.a' but it should be:

'/Users/zhack013/Library/Mobile Documents/com~apple~CloudDocs/Workspace/Perso/Missions/KISAPP/Code/kisapp/ios/.symlinks/plugins/fast_rsa/ios/librsa_bridge.a'

Because there is a space in my path it doesn't work...

Could you help me ?
And it also doesn't work on version 3.0.1

Thanks !

**Comment by jerson** [comment]
Hi @ZacharieAzoulai thanks for report the issue, seems like a path issue in cocoapods, please for now use 3.0.0 im gonna research to find a good solution

**Comment by jerson** [comment]
Hi @ZacharieAzoulai could help me to test with https://pub.dev/packages/fast_rsa/versions/3.0.3 version please, path issue was fixed at least on my local tests

**Comment by ZacharieAzoulai** [comment]
Hi @jerson, it worked !
