### ISSUE TITLE
The RSA sign can not be verified by other language

### ISSUE THREAD

**Issue by seanhann** [jerson/flutter-rsa#23]
I did a RSA.signPKCS1v15Bytes signature by fast_rsa, it can be verified by nodejs. But same nodejs logic could verify the java signature.

**Comment by jerson** [comment]
hey @seanhann thanks for report the issue, can you share a code example to try to reproduce it here please

**Comment by seanhann** [comment]
Use fast_rsa generated the signature like following:
```
  static Future<String> sign(message) async {
    var res = await RSA.signPKCS1v15Bytes(Uint8List.fromList(message.codeUnits), Hash.SHA256, privateKey);
    return hex.encode(res);
  }
```

And nodejs verified it like(following code works for java generated signature):
```
 const verify = crypto.createVerify('RSA-SHA256');
  verify.update(data.message);

   const sigBuf = Buffer.from(data.sign, 'hex');
   console.log(sigBuf);
   if(verify.verify('-----BEGIN PUBLIC KEY-----\n'+data.publicKey+'\n-----END PUBLIC KEY-----', sigBuf)){
       console.log("publish verified");
   }

```

**Comment by jerson** [comment]
@seanhann  please try again with latest version we fixed that before
