### ISSUE TITLE
Error in Flutter Web, Asset Problem

### ISSUE THREAD

**Issue by TicketMarketTecnologia** [jerson/flutter-rsa#26]
I'm getting an error while using FAST_RSA with Flutter Web. In the Android version works normally. I checked the Console for this  error. I was trying using in Debug mode with Chrome.
![625a001a-3c08-4fdc-9de7-5a996dae8bab](https://user-images.githubusercontent.com/62756995/145098980-506ea009-e100-44d0-8605-383ac6b04001.jpg)
r.

**Comment by jerson** [comment]
hi @TicketMarketTecnologia have you added those assets to you deps


add to you `pubspec.yaml`

```yaml
assets:
  - packages/fast_rsa/web/assets/worker.js
  - packages/fast_rsa/web/assets/wasm_exec.js
  - packages/fast_rsa/web/assets/rsa.wasm
```

ref: https://github.com/jerson/flutter-rsa/blob/master/example/pubspec.yaml
please read more in: https://github.com/jerson/flutter-rsa#web
