### ISSUE TITLE
Using generated public key in golang

### ISSUE THREAD

**Issue by patachi** [jerson/flutter-rsa#27]
**Background :**

For RSA private key & public key **PKCS1**, **PKCS8** & **PKCS1**, **PKIX** formats are available.
**PKCS1** format is _primarily only_ used for the RSA algorithm and they have different headers.

private key **PKCS1** format header : `-----BEGIN RSA PRIVATE KEY-----`
private key **PKCS8** format header : `-----BEGIN PRIVATE KEY-----`

public key **PKCS1** format header : `-----BEGIN RSA PUBLIC KEY-----`
public key **PKIX** format header : `-----BEGIN PUBLIC KEY-----`

ref : https://pkg.go.dev/crypto/rsa

 

**Problem :**

The generated public key is in **PKIX** format and it can not be parsed in Golang (using standard lib for RSA)
and by changing the header to **PKCS1** format (as golang indicates in its error) it can be parsed but the encrypted data can not be decrypted by its own private key.

**Steps to Reproduce :**

Here is a Golang code snippet for parsing public key in both PKIX&PKCS1 formats and encrypting some plain text data.
You can generate a new key pair in dart/flutter and run this code snippet online to parse & encrypt by the generated public key
And try to decrypt the result again in dart/flutter.

https://go.dev/play/p/4D9ej_jszsU

**Comment by jerson** [comment]
Hi @patachi thanks for report the issue, I didnt know that, based on what you said we should update headed based on type, im gonna update in rsa-mobile this weekend
https://github.com/jerson/rsa-mobile/blob/64cc9c47a72469260ab7a0ff6f0fa6d0efca0732/rsa/codec.go#L151

**Comment by patachi** [comment]
Yes, the lines [145](https://github.com/jerson/rsa-mobile/blob/64cc9c47a72469260ab7a0ff6f0fa6d0efca0732/rsa/codec.go#L145) & [178](https://github.com/jerson/rsa-mobile/blob/64cc9c47a72469260ab7a0ff6f0fa6d0efca0732/rsa/codec.go#L178) should change based on `formatType`.

And also I recommend using `pem.Encode` instead of `pem.EncodeToMemory` (line [143](https://github.com/jerson/rsa-mobile/blob/64cc9c47a72469260ab7a0ff6f0fa6d0efca0732/rsa/codec.go#L143) & [176](https://github.com/jerson/rsa-mobile/blob/64cc9c47a72469260ab7a0ff6f0fa6d0efca0732/rsa/codec.go#L176)) like the sample code below to ensure the result got flushed, just in case to prevent leaving any loose end to compiler and how cross platforms handle things like memory isolation.

```
func encodePem(b *pem.Block)([]byte, error){
	buf:=new(bytes.Buffer)
	w:=bufio.NewWriter(buf)
	if err:=pem.Encode(w,b);err!=nil{
		return nil, err
	}
	if err:=w.Flush();err!=nil{
		return nil, err
	}
	return buf.Bytes(),nil
}
```

**Comment by jerson** [comment]
Hey @patachi I just released a new version with the fix please take a look

https://pub.dev/packages/fast_rsa/versions/3.2.0

here is the commit for reference: https://github.com/jerson/rsa-mobile/commit/18c4c418b73e8f3a609aadd14ca7f1ac81b872e9

**Comment by patachi** [comment]
Thanks, great job. probably #19 & #23  Issues have been fixed by this patch too.
