### ISSUE TITLE
module 'fast_rsa' not found @import fast_rsa; on Mac with M1 chip

### ISSUE THREAD

**Issue by VovaMedvediev** [jerson/flutter-rsa#30]
Hi!

I can't build iOS project on Mac with M1 chip - GeneratedPluginRegistrant.m:24:9: fatal error: module 'fast_rsa' not found @import fast_rsa;

On the previous laptop with Intel Chip everything was ok.

Commenting fast_rsa plugin resolves the issue... But I need this plugin to use :)

If any info should be provided - please let me know

**Comment by jerson** [comment]
Hi @VovaMedvediev thanks for report this issue, could you provide me info about which versions are you using, flutter, fast_rsa and a `flutter doctor` output

**Comment by VovaMedvediev** [comment]
@jerson 
fast_rsa: ^3.2.0

Flutter 2.8.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision cf44000065 (4 weeks ago) • 2021-12-08 14:06:50 -0800
Engine • revision 40a99c5951
Tools • Dart 2.15.0

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.8.0, on macOS 12.1 21C52 darwin-arm, locale en-UA)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] Connected device (2 available)
    ! Error: Vova’s iPhone is busy: Preparing the watch for development via Vova’s iPhone. Xcode will continue when Vova’s iPhone is finished. (code -10)

• No issues found!
volodymyrmedvediev@MacBook-Air-admin simple % flutter doctor -v
[✓] Flutter (Channel stable, 2.8.0, on macOS 12.1 21C52 darwin-arm, locale en-UA)
    • Flutter version 2.8.0 at /Users/volodymyrmedvediev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cf44000065 (4 weeks ago), 2021-12-08 14:06:50 -0800
    • Engine revision 40a99c5951
    • Dart version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/volodymyrmedvediev/Library/Android/sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] Connected device (2 available)
    • Vova’s iPhone (mobile) • 00008030-0014119A0A82802E • ios            • iOS 15.1 19B74
    • Chrome (web)           • chrome                    • web-javascript • Google Chrome 96.0.4664.110
    ! Error: Vova’s iPhone is busy: Preparing the watch for development via Vova’s iPhone. Xcode will continue when Vova’s iPhone is finished. (code -10)

• No issues found!

**Comment by Zheyuan-Robert-Xu** [comment]
Hi @jerson,
I have the similar error in using fast_rsa: ^3.1.0 in Mac M1.
And the Doctor summary.
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-arm, locale en-AU)
    • Flutter version 2.8.1 at /Users/user/Documents/software/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (5 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/Library/Android/sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.32.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.1 21C52 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 97.0.4692.71

• No issues found!

**Comment by jerson** [comment]
Hi, thanks for report the issue, Seems like is an issue related with M1 arch, so im gonna try building binaries for apple m1, probably it will take a while since i need to run a cloud Mac M1 in order to test

**Comment by Zheyuan-Robert-Xu** [comment]
Thanks for your contribution.

**Comment by jerson** [comment]
Hi @Zheyuan-Robert-Xu im testing on M1 and is working with this new release https://pub.dev/packages/fast_rsa/versions/3.3.0 

could you help me to confirm that please

to run in simulator im using

`flutter run `

and for build im using xcode
`Xcode / product / archive `

![remmina_macOSScaleway_51 159 120 23_20220204-200556](https://user-images.githubusercontent.com/325780/152596894-aac0ed3a-4188-4037-95ab-1f554b807fa4.png)

**Comment by Zheyuan-Robert-Xu** [comment]
Thanks @jerson , it works now. And the desktop app can work with macos M1.
