### ISSUE TITLE
infinity waiting when rsa sign

### ISSUE THREAD

**Issue by cwangfr** [jerson/flutter-rsa#33]
Hi, I have a strange problem here. When I use the RSA SignPSS feature, there is an infinite wait.
I use Android Studio, use usb cable connect with my Samsung Tab7.
If I start program on device, keep usb cable connect, the function always ok,
but, when I start program, and then disconnect the usb cable, the signPSS could not return result.
here is my code :

    final _pkcs12KeyPair = await RSA.convertPKCS12ToKeyPair(
        (await rootBundle.loadString('assets/key.base64')), "miipos");
    var signature = await RSA.signPSS(
        value, Hash.SHA512, SaltLength.AUTO, _pkcs12KeyPair.privateKey); // always waiting there, never return the result signature

    var result = signature.replaceAll("+", "-").replaceAll("/", "_");
    debugPrint(result);
    debugPrint("****** end sign ******");

thanks

**Comment by zaqzaq163** [comment]
Have you found a solution?

**Comment by zaqzaq163** [comment]
Hi @jerson, I use IOS device, when I transfer code from swift to objective-c and submit to testflight, signPKCS1v15 can't return result and wait infinitely

**Comment by jerson** [comment]
@zaqzaq163 which version are you using?

**Comment by zaqzaq163** [comment]
I have tested version 3.5.3 and 3.5.6, it doesn't work

**Comment by jerson** [comment]
Hi @zaqzaq163 I'm still trying to reproduce it, but I couldn't, could you provide me a full example with a sample private key or a pkcs12 and the arguments you are using

**Comment by jerson** [comment]
@zaqzaq163 I just released a new version, please take a look when you get a chance https://pub.dev/packages/fast_rsa/versions/3.5.7 if doesn't work either please send me a full example to try to reproduce it here, thank you.
