### ISSUE TITLE
Encryption fails on Safari

### ISSUE THREAD

**Issue by sils** [jerson/flutter-rsa#36]
Hey,

we use this in our app and it works great in web and mobile - except on Safari (mobile and desktop).

Here's a screenshot of the respective error in the JS console:

![image](https://user-images.githubusercontent.com/5716520/163412721-e8ad675d-ee60-4a9e-b8dc-a7470bcf7ebe.png)

In our code we're essentially doing this:

`return await RSA.encryptPKCS1v15(message, publicKey);`

**Comment by sils** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WebAssembly/instantiateStreaming it seems this is supported by safari 15 upwards which only got released half a year ago, checking with our testers. Seems safari users are just a little old fashioned... yet they are likely a not too insignificant portion of the mobile userbase.

I wonder if there's a way to make it backwards compatible...

**Comment by jerson** [comment]
Hey @sils thanks for report the issue, I think i can replace instantiateStreaming using 

```js
fetch('simple.wasm').then(response =>
  response.arrayBuffer()
).then(bytes =>
  WebAssembly.instantiate(bytes, importObject)
)
```

let me run some tests here and then we will be supporting from Safari 11

**Comment by jerson** [comment]
Update: Please try this new version https://pub.dev/packages/fast_rsa/versions/3.4.7

main changes https://github.com/jerson/flutter-rsa/commit/65620f5e55317880a7521400a5f7964347284ef1#diff-2fdc69bca430e9590568563c103bfc3a1b1460a46c7eaefc51c8cd3fe7cd6881R5-R57

**Comment by jerson** [comment]
@sils any news on this, did you already tested ?

**Comment by sils** [comment]
Yep, this works!
