### ISSUE TITLE
`Execution failed for task ':fast_rsa:stripReleaseDebugSymbols'` when building for Android

### ISSUE THREAD

**Issue by nilsreichardt** [jerson/flutter-rsa#37]
## Description
We have the problem that we can't build anymore for our CI. When we try to build with Codemagic or GitHub Actions, we get this error:

```
* What went wrong:
Execution failed for task ':fast_rsa:stripReleaseDebugSymbols'.
> 1 exception was raised by workers:
  org.gradle.process.internal.ExecException: A problem occurred starting process 'command '/usr/local/share/android-sdk/ndk/24.0.8215888/toolchains/llvm/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-strip''
```

GitHub Actions logs:
* https://github.com/SharezoneApp/sharezone-app/runs/6477977081?check_suite_focus=true

Source code of our app: https://github.com/SharezoneApp/sharezone-app

We are using version `3.4.7` of `fast_rsa` and `2.10.5` of Flutter.

**Comment by jerson** [comment]
HI @nilsreichardt could you try  updading subosito/flutter-action action, seems related to that

subosito/flutter-action@v1

to 

subosito/flutter-action@main

**Comment by nilsreichardt** [comment]
Thanks for the quick response, @jerson.

Unfortunately, it's still failing:
* https://github.com/SharezoneApp/sharezone-app/runs/6485434158?check_suite_focus=true (using `macos-latest`)
* https://github.com/SharezoneApp/sharezone-app/runs/6485664315?check_suite_focus=true (using `ubunto-latest`)
* https://codemagic.io/app/6274fcfc87c748ce531c7376/build/6283fe3707752f8a7597ac0a (using M1 Mac Mini)
* https://codemagic.io/app/6274fcfc87c748ce531c7376/build/6283fcfe290c45a02abc9078 (using Mac Pro)

I don't why, but the premium VMs of Codemagic it's working:
* https://codemagic.io/app/6274fcfc87c748ce531c7376/build/6284a958178d245cdb220982
