### ISSUE TITLE
[Bug] DLL load fails in unit test

### ISSUE THREAD

**Issue by Genora51** [jerson/flutter-rsa#40]
In my flutter app I have unit tests which call into `fast_rsa`. However, the tests fail to load `librsa_bridge.dll`.

### Example: `rsa_test.dart`
```dart
import 'package:fast_rsa/fast_rsa.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  test("RSA", () async {
    await RSA.generate(2048);
  });
}
```
### Error:

    Invalid argument(s): Failed to load dynamic library 'librsa_bridge.dll': error code 126
    dart:ffi                                     new DynamicLibrary.open
    package:fast_rsa/bridge/binding.dart 119:33  Binding.openLib
    package:fast_rsa/bridge/binding.dart 25:16   new Binding._internal
    package:fast_rsa/bridge/binding.dart 16:45   Binding._singleton
    package:fast_rsa/bridge/binding.dart         Binding._singleton
    package:fast_rsa/bridge/binding.dart 21:12   new Binding
    package:fast_rsa/fast_rsa.dart 38:32         RSA.bindingEnabled
    package:fast_rsa/fast_rsa.dart               RSA.bindingEnabled
    package:fast_rsa/fast_rsa.dart 41:9          RSA._call
    package:fast_rsa/fast_rsa.dart 77:22         RSA._keyPairResponse
    package:fast_rsa/fast_rsa.dart 435:18        RSA.generate
    test\rsa_test.dart 6:15                      main.<fn>
    test\rsa_test.dart 5:15                      main.<fn>

**Comment by jerson** [comment]
Hi, yeah currently RSA can only be tested in integration tests, see examples: https://github.com/jerson/flutter-rsa/blob/master/example/integration_test/app_test.dart

**Comment by jerson** [comment]
or if you are using windows you can copy .dll from ( https://github.com/jerson/flutter-rsa/tree/master/windows/shared) to system32 windows and will be installed in your device, not sure if will work, but it can be an option
