### ISSUE TITLE
Failed to load dynamic library '.../librsa_bridge.so'

### ISSUE THREAD

**Issue by duocnguyen6799** [jerson/flutter-rsa#42]
My Flutter app distributed on the Google Play store seems to be unable to load a packaged dynamic library on a few Android devices **(less than Android 6.0)**.

**Actual results:**
`
Failed to load dynamic library '/data/data/my_package/lib/librsa_bridge.so': dlopen failed: '/data/data/my_package/lib/librsa_bridge.so' not found
`

**Expected results:**
The library is loaded successfully.

**Flutter doctor output**
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, 2.10.3, on macOS 13.0 22A380 darwin-x64, locale en-VN)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.73.1)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!
```

**Comment by ernestoA92** [comment]
Same here

**Comment by jerson** [comment]
Hi @duocnguyen6799 @ernestoA92  thanks for report this issue, im gonna take a look in some weeks

**Comment by MrTilaris** [comment]
The same issue here. Please, help.

**Comment by jerson** [comment]
Hi @MrTilaris which flutter and fast-rsa version are you using?

**Comment by MrTilaris** [comment]
Hi! Thanks for rapid reaction!

Flutter 3.7.1 
fast_rsa: ^3.5.3

I'm using fast_rsa in my private flutter plugin that I'm using in my projects. 
So, in my plugin when I running instrumental tests there is this error. On every platform.

dart:ffi                                     new DynamicLibrary.open
package:fast_rsa/bridge/binding.dart 117:33  Binding.openLib
package:fast_rsa/bridge/binding.dart 26:16   new Binding._internal
package:fast_rsa/bridge/binding.dart 17:45   Binding._singleton
package:fast_rsa/bridge/binding.dart         Binding._singleton
package:fast_rsa/bridge/binding.dart 22:12   new Binding
package:fast_rsa/fast_rsa.dart 40:32         RSA.bindingEnabled
package:fast_rsa/fast_rsa.dart               RSA.bindingEnabled
package:fast_rsa/fast_rsa.dart 43:9          RSA._call
package:fast_rsa/fast_rsa.dart 79:22         RSA._keyPairResponse
package:fast_rsa/fast_rsa.dart 437:18        RSA.generate
package:bstoken_core/dpass.dart 240:16       DPass.generateKeyPair
test/dpass_test.dart 45:33                   main.<fn>

Invalid argument(s): Failed to load dynamic library 'librsa_bridge.dylib': dlopen(librsa_bridge.dylib, 0x0001): tried: 'librsa_bridge.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibrsa_bridge.dylib' (no such file), '/Users/pavelshinkarev/flutter/bin/cache/artifacts/engine/darwin-x64/./librsa_bridge.dylib' (no such file), '/Users/pavelshinkarev/flutter/bin/cache/artifacts/engine/darwin-x64/../../../librsa_bridge.dylib' (no such file), '/Users/pavelshinkarev/flutter/bin/cache/artifacts/engine/darwin-x64/Frameworks/librsa_bridge.dylib' (no such file), '/Users/pavelshinkarev/flutter/bin/cache/artifacts/engine/darwin-x64/./librsa_bridge.dylib' (no such file), '/Users/pavelshinkarev/flutter/bin/cache/artifacts/engine/darwin-x64/../../../librsa_bridge.dylib' (no such file), '/Users/pavelshinkarev/flutter/bin/cache/artifacts/engine/darwin-x64/Frameworks/librsa_bridge.dylib' (no such file), '/usr/lib/librsa_bridge.dylib' (no such file, not in dyld cache), 'librsa_bridge.dylib' (no such file), '/usr/local/lib/librsa_bridge.dylib' (no such file), '/usr/lib/librsa_bridge.dylib' (no such file, not in dyld cache)



But when I'm using my plugin (with fast_rsa dependency) in application it is working well. Maybe there are some recommendations: how to use your beautiful lib to work with tests?)

**Comment by jerson** [comment]
Hi @duocnguyen6799, @MrTilaris , @ernestoA92 I'm going to release a version for this, this is the PR just in case you want to take a look https://github.com/jerson/flutter-rsa/pull/47

**Comment by jerson** [comment]
New version released https://pub.dev/packages/fast_rsa/versions/3.5.5 please try with this one, feel free to reopen the issue if its needed

**Comment by xxMrPHDxx** [comment]
I'm using version fast_rsa: ^3.6.6 but still have same issue
