### ISSUE TITLE
Public key is invalid

### ISSUE THREAD

**Issue by sarangip** [jerson/flutter-rsa#45]
String encrypted = await RSA
        .encryptPKCS1v15("Hello", "public key")
        .catchError((e) => onError(e));
    print(encrypted);

--------------------------------------------------------------------------------------
response:

invalid public key

**Comment by jerson** [comment]
Hi, please take a look at this example https://github.com/jerson/flutter-rsa/blob/master/example/lib/encrypt_decrypt_pkcs.dart

**Comment by jerson** [comment]
Im closing this for now, please feel free to re-open if its needed
