### ISSUE TITLE
Seed RSA Generator

### ISSUE THREAD

**Issue by sebastianbuechler** [jerson/flutter-rsa#61]
Is there a way to seed the RSA generator of this package like we can do with pointy castle: https://github.com/bcgit/pc-dart/blob/master/tutorials/rsa.md

If no, what determines the seed here?

**Comment by jerson** [comment]
Hi @sebastianbuechler currently we don't support using a custom seed to geneate a key, currently we use rand.Reader from go

https://github.com/jerson/rsa-mobile/blob/master/rsa/generate.go#L16
> From go docs:
> Most applications should use [crypto/rand.Reader] as rand. Note that the
> returned key does not depend deterministically on the bytes read from rand,
> and may change between calls and/or between versions.

so after read more in deep it seems is something we can adjust to make it safer

---
it seems we should also allow to set a custom nprime value, which is 2 by default
> From go docs:
> The use of this function with a number of primes different from
> two is not recommended for the above security, compatibility, and performance
> reasons. Use GenerateKey instead.
