### ISSUE TITLE
when i am trying to encrypt a text using this library i am getting this issue invalid arguments like that , i am using public key and plain text for rsa encryption. 

### ISSUE THREAD

**Issue by Jassirlink** [jerson/flutter-rsa#63]
error message :
Invalid argument(s): Failed to load dynamic library '/data/data/com.app.engapp.app/lib/librsa_bridge.so': dlopen failed: library "/data/data/com.app.engapp.app/lib/librsa_bridge.so" not found

**Comment by jerson** [comment]
Hi, could you provide more detail about the android && library version you are using

**Comment by rafifitra-venturo** [comment]
The issue still occurs on devices with SDK 35 support for 16KB. This may be due to a new policy from Android and the Play Store.

<img width="688" height="676" alt="Image" src="https://github.com/user-attachments/assets/d6aa16ce-d5dc-4b3d-ba7d-13604aa5d87b" />
