### ISSUE TITLE
Error while trying to load an asset: Failed to load asset at "assets/packages/fast_rsa/web/assets/rsa.wasm" (404)

### ISSUE THREAD

**Issue by flowhorn** [jerson/flutter-rsa#7]
I cant use this on Web because of this issue. Running latest flutter master.

**Comment by jerson** [comment]
hi @flowhorn you should check example

is required to add to you pubspec.yaml

```
  assets:
    - packages/fast_rsa/web/assets/wasm_exec.js
    - packages/fast_rsa/web/assets/rsa.wasm
```
ref: https://github.com/jerson/flutter-rsa/blob/master/example/pubspec.yaml


and in you index.html
```

  <script src="assets/packages/fast_rsa/web/assets/wasm_exec.js" type="application/javascript"></script>
```
ref: https://github.com/jerson/flutter-rsa/blob/master/example/web/index.html

on these days im going to add this to readme for clarify to everyone
