### ISSUE TITLE
The argument type 'JSString' can't be assigned to the parameter type 'String'.

### ISSUE THREAD

**Issue by sAw-hTet-nAing** [jerson/flutter-rsa#76]
With Flutter 3.24.0,I'm having this issue in flutter web.
[View Img](https://github.com/user-attachments/assets/9ea86e57-e266-4fbf-8df6-de57b7761b2c)

**Comment by Sunilk047** [comment]
I am also getting the same error
![IMG_20240812_184320467](https://github.com/user-attachments/assets/e970a0b1-9958-43bb-99f5-94dc25314d77)

**Comment by guicima** [comment]
Same here with Flutter 3.22.3

**Comment by jerson** [comment]
seems related to the SDK update, could you use v3.6.3 version in the mid time please

**Comment by sAw-hTet-nAing** [comment]
> seems related to the SDK update, could you use v3.6.3 version in the mid time please

Sure

**Comment by cdawei** [comment]
If you use Flutter3.24/Dart 3.5, a workaround is to change Line 11 of `.pub-cache/hosted/pub.dev/fast_rsa-3.6.4/lib/web/rsa_web.dart` from
```dart
'assets/packages/fast_rsa/web/assets/worker.js'.toJS,
```
to
```dart
'assets/packages/fast_rsa/web/assets/worker.js',
```
then rebuild your app.

**Comment by sAw-hTet-nAing** [comment]
> If you use Flutter3.24/Dart 3.5, a workaround is to change Line 11 of `.pub-cache/hosted/pub.dev/fast_rsa-3.6.4/lib/web/rsa_web.dart` from
> 
> ```dart
> 'assets/packages/fast_rsa/web/assets/worker.js'.toJS,
> ```
> 
> to
> 
> ```dart
> 'assets/packages/fast_rsa/web/assets/worker.js',
> ```
> 
> then rebuild your app.

Thank you for the temporary solution. While I do prefer a long-term fix, I'm currently fine with using other versions, except for 3.6.4. I just wanted to report this issue so that the admin is aware. Now that it's been brought to their attention, I'll go ahead and close the issue.

**Comment by jerson** [comment]
Hi @sAw-hTet-nAing could you share the environment from you pubspec.yaml, I just tested in an new empty project and works fine with the `toJS` 

```yaml
environment:
  sdk: ^3.5.0
```

**Comment by sAw-hTet-nAing** [comment]
Hi,@jerson ,Thanks for the update! My current SDK is as follow.
```
environment:
  sdk: ">=3.4.3 <4.0.0"
```
This might be causing the issue. I'll change my SDK version and test again.

**Comment by sAw-hTet-nAing** [comment]
Hello @jerson ,

Still having the issue even after changing to `sdk: ^3.5.0`.
Tried Methods
```
flutter clean pub cache
flutter clean && flutter pub get
flutter pub upgrade
```
and also tested by deleting `pubspec.lock`.
Still having the same issue.
