### ISSUE TITLE
Error: The argument type 'String' can't be assigned to the parameter type 'JSAny'.

### ISSUE THREAD

**Issue by AmirsalarSalehiDevlop** [jerson/flutter-rsa#79]
Target dart2js failed: ProcessException: Process exited abnormally with exit code 1:
/C:/Users/user/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/fast_rsa-3.6.5/lib/web/rsa_web.dart:10:27:
Error: The argument type 'String' can't be assigned to the parameter type 'JSAny'.
  Worker worker = Worker( 'assets/packages/fast_rsa/web/assets/worker.js');

the issue is fixed by:

`Worker worker = Worker( 'assets/packages/fast_rsa/web/assets/worker.js'.toJS);`

just add .toJS at then end of the string.

Please fix this and publish new version

**Comment by jerson** [comment]
Thanks for report this issue, this is the new version "https://pub.dev/packages/fast_rsa/versions/3.6.6"
