### ISSUE TITLE
Add support for importing RSA keys in JWK format

### ISSUE THREAD

**Issue by acolytec3** [jerson/flutter-rsa#8]
@jerson Any suggestions on how to get from a JWK format key file (as described [here](https://stackoverflow.com/questions/24093272/how-to-load-a-private-key-from-a-jwk-into-openssl)) to the PKCS12 format private key you're using for the PSS signer function?  I'm working on an app that needs RSA-PSS signatures and manages private keys using JWK format keys so I had to write native code for the signature section.  I'd love to use your library to do the signatures and get rid of my Android specific implementation.

**Comment by acolytec3** [comment]
For reference, this is what I'm having to do at present.  In Dart/Flutter, take the public and private key parameters from the JWK [here](https://github.com/acolytec3/ArMob/blob/7c48450a068defe9faef0162375eb9116eba8a1c/lib/transaction.dart#L67) and then passing it to Kotlin to do the signature [here](https://github.com/acolytec3/ArMob/blob/7c48450a068defe9faef0162375eb9116eba8a1c/android/app/src/main/kotlin/com/example/arweave/MainActivity.kt#L37) and then pass the resulting signature back to Flutter for further processing.

**Comment by jerson** [comment]
hi @acolytec3 this weekend i'm going to search about that, thanks

**Comment by acolytec3** [comment]
@jerson What is the format of the pkcs12 string in the example (pfx,pem, etc)?  I tried pasting it into a certificate decoder and it wasn't recognized.  Just trying to understand what format the source string is supposed to be in so I can figure out how to get from the Java Web Key to whatever input your library uses.

**Comment by acolytec3** [comment]
@jerson So I dug into your go code a bit and I think the answer I would need is to just be able to pass in an RSA private key to the PSSSigner function.  It looks like your signer module in Go isn't using the certificate part of the PKCS12 format [anyway](https://github.com/jerson/rsa-mobile/blob/48a6ccd6184a1ae8390b0e4e8a155c2e57ccb384/rsa/sign_pss.go#L13) so any chance you could just add another version of the SignPSS method that accepts an RSA private key as a parameter instead of a PKCS12 certificate (since Dart doesn't have native PKCS12 certificate support anywhere anyway as far as I can tell)?

**Comment by jerson** [comment]
hi @acolytec3 yes the format is pfx and maybe should i create a method for use directly with private key instead of pkcs12

**Comment by acolytec3** [comment]
I'll experiment with it today and see if I can do so. Not a go expert but
I'll try.  What's the make target on the rsa-mobile to build for Flutter?

**Comment by jerson** [comment]
```bash
make android
make ios
```

**Comment by acolytec3** [comment]
Looks like you updated this on the native code side to accept an RSA private key?  Excited to try it out once you merge that change here as it solves a huge pain point for the app I'm working on.  Thanks!

**Comment by jerson** [comment]
hi @acolytec3 could you try with 1.0.0 version there are a lot of changes but i think that now is more stable API

https://pub.dev/packages/fast_rsa/versions/1.0.0

**Comment by acolytec3** [comment]
Will do. Just pulled it into my app and will let you know if the sign function works as expected.

**Comment by acolytec3** [comment]
I've tried using and  while it does compile, it's not producing the correct signatures.  It looks like the RSA private key its generating from my jwk is different than the one that is produced by Kotlin (which is how I'm doing RSA-PSS signing today so not sure what to make of that.

**Comment by jerson** [comment]
hi @acolytec3 maybe you should use

RSASaltLength.equalsHash instead of RSASaltLength.auto

**Comment by acolytec3** [comment]
I believe the root of the issue is the way the private key is being generated.   I printed the private key generated by the kotlin code and it does not match the private key generated by `rsa-mobile`.  Is the `keyID` field of any importance?

**Comment by jerson** [comment]
keyID is optional just is for select a custom JWK

**Comment by jerson** [comment]
can you share a JWK for create a test on rsa-mobile and the expected output

**Comment by acolytec3** [comment]
https://gist.github.com/acolytec3/c327b1211f3b25d65272fb1f842cec99

The input string is a base64Url encoded string.

My Kotlin code is using a byteArray so I have to encode the string to be signed using `base64Url.encode` to make it equivalent to what I pass to your `signPSS` method.

**Comment by jerson** [comment]
remember that PSS always generates different signed code unlike PKCS1v15

**Comment by jerson** [comment]
and you should  use base64 instead of base64Url because we only support base64

**Comment by jerson** [comment]
and for you sign method you are using  **ByteArray**

`call.argument<ByteArray>("rawTransaction")`

and the library only support string, that means that before sign you should convert to base64

**Comment by jerson** [comment]
check this test for more details

https://github.com/jerson/rsa-mobile/commit/78e208116195f2a2b00715c60ce38c4e8461a5a7

**Comment by acolytec3** [comment]
I'm not sure what to tell you but it's not producing correct results for me.  I need to use RSA PSS signatures for signing blockchain transactions for my app and transactions signed with your package unfortunately are getting rejected with an error of `transaction verification failed` where as they are accepted using the kotlin method I referenced above.  Here's the code where I'm trying to use your signing method.  https://github.com/acolytec3/ArMob/commit/f4e62f0f62fcba6c2203c7358a8eacab4522636d

Note that I am converting my raw data from bytes to base64 strings before signing so something is going awry.

**Comment by jerson** [comment]
you signature is generated using ByteArray, here you should convert to base64 and then to bytearray again before sign too, check this line, https://github.com/acolytec3/ArMob/blob/fast_rsa/android/app/src/main/kotlin/com/example/arweave/MainActivity.kt#L17

**Comment by acolytec3** [comment]
I don't think that's the solution.  My existing kotlin code produces signatures that are accepted by the blockchain node and this blockchain works with base64URL encoded strings and not base64.  I would have to re-engineer large sections of code to work with base64 and I already know that base64 encoded strings are rejected by the blockchain and I'm guessing that something is getting lost or added during the bytes -> base64 -> sign -> bytes conversion process that's causing the transactions to be rejected by the node.  I think I'm going to give up at this point and work on a swift implementation of my existing code for the iOS version of the app.

**Comment by acolytec3** [comment]
I've been working on a fork of your rsa-mobile repo that uses a bytesArray but having trouble getting it to work with my local fork of `flutter-rsa`.  This [commit](https://github.com/acolytec3/rsa-mobile/commit/57e06bcbad5a98935228a3d7e14060ed0fe23d36) compiles and I've updated the corresponding code elements in flutter-rsa in a local fork but the plugin won't build when I pull it into my app.  It throws some generic Android error so was wondering if you'd be willing to just expose a second SignPSSwithBytes method since the underlying RSA signing method you're using signs with bytes and not a Base64 string anyway.

**Comment by jerson** [comment]
hi @acolytec3 thank you im gonna check and maybe i was thinking in have a last argument with option for choose use base64 or bytes since gomobile dont support byte array as i know

**Comment by acolytec3** [comment]
Just checking back in on this. Have you had any luck? [This](https://medium.com/flutter-community/using-go-library-in-flutter-a04e3496aa05) seems to indicate byte slices are available in Go mobile so seems like it should work.

**Comment by jerson** [comment]
great, I didn't know, implement the feature these days

**Comment by jerson** [comment]
hi @acolytec3 could you try with 1.0.1 version, there are new Bytes Methods

https://pub.dev/packages/fast_rsa/versions/1.0.1

```dart

var result = await RSA.signPSSBytes(messageBytes, RSAHash.sha512, RSASaltLength.auto, privateKey)
var result = await RSA.signPKCS1v15Bytes(messageBytes, RSAHash.sha512, privateKey)

var result = await RSA.verifyPSSBytes(signatureBytes, messageBytes, RSAHash.sha512, RSASaltLength.auto, publicKey)
var result = await RSA.verifyPKCS1v15Bytes(signatureBytes, messageBytes, RSAHash.sha512, publicKey)
```

**Comment by acolytec3** [comment]
I'm getting the below error when I try to compile now.  Any idea what this means?  I blew away my repo and pulled it fresh from github and added `fast_rsa` and it's still throwing this error.
```
Execution failed for task ':fast_rsa:mergeDebugJavaResource'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Non-directory inputs must have .jar extension: /home/jim/flutter/.pub-cache/hosted/pub.dartlang.org/fast_rsa-1.0.1/android/libs/rsa.aar
```

**Comment by acolytec3** [comment]
Thank you for doing this.  Unfortunately, initial attempts produced the same result as before with both `SaltLength.auto` and `SaltLength.equalsHash` where the signed transactions are rejected by the node.  I'll do some more experimenting the next day or two and see if there's anything else that jumps out at me.

**Comment by jerson** [comment]
Hi, please test with this comment 
https://github.com/acolytec3/ArMob/commit/2fbb7f3abfa02a230123a85d295de1c502a133e6#r38450011

**Comment by jerson** [comment]
cc @acolytec3

**Comment by acolytec3** [comment]
Tested and still failing.  When I sign and then use `verifyPSSBytes` as [here[(https://github.com/acolytec3/ArMob/compare/fast_rsa#diff-43ab103811e503422c14be92b21bec5eR83), flutter throws an error 
`Platform error occurred: PlatformException(error, x509: unknown format, null)`.  Is it possible your `convertJWKtoPrivateKey` conversion method isn't working right?

There's a Go implementation of the overall Arweave API that looks like it uses the same underlying `crypto` library and it looks like that library uses the `auto` salt length so at this point I'm assuming it's not the `signPSSBytes` signing method that's failing.

**Comment by acolytec3** [comment]
Another follow-up here.  Just for fun, I ran the [`jwk-to-pem`](https://runkit.com/embed/spqpspj8xc9b/) method on the example jwk you used and it seems to generate a different PEM format private key than what `rsa-mobile` produces.  Below is the private key generated by your `convertJWKToPrivateKey` method:
```
YtFFg4bJjOFv3T38nCZmDh8lYjm25/1qILalsB0XRoDxQy9FLxWb4zd09JsDhL0E
YAQ/hNfOnQFVOBtYEHVYMCHYH6GoTcNgxmUkZPk4AfpAqZmjDzKfVJrw4Fr68pPT
EQOQEzBcIWp61P21BSkhqO4QuFinkQsSH6NdTB/3FpbhYf34Hjf+iH7hdpdWo4ao
RLb8eZeZcqBRZoRmlhQnOD+PVxQR/vb9rjXSjGkCWwRbsurVLWdBh/FQn0S9Q6EH
qiV8nbW+R0Rk2E76JwgMFkqGUtZj8DeEqXJ2jlAvuzp56fXeAViPEtvUj1HheO8O
3LxdVYCiapWWKq4qQVoRzdiyvydYSmbztgFUhekvmjNkxLNKOh71i3hFtoXycegq
Z6izrUGoF2oD24lsTKsV5lV5pwfmUjVvxtHZm54bJIMfUDYbOV6yeDjYBb8CAwEA
AQKCAgAR49Ksl4Wfh/RryujM8TCcwJ5CZ0o7dDY/BitIkRLwKH0hvOykNeplOGSx
Mkd7JrZZcPg7e+WeRFFrmelg6KadN5U7oM7542OWCQCGGwQGHmPNFh4KEgMzNV0I
rVjufdr/EILGIYyT+e15bb+quqwrL0q2gv3SdKZ2hX1v0LG8E+EUbJDKQXs86RXR
91toika1xrII0nhmAzJSlaLRnCBSHFNS0ayYuUs3Y+GD6+3+Nn3qHmV
```

**Comment by acolytec3** [comment]
FYI here - thanks for trying to resolve my particular issue but I've ended up building my own RSA-PSS signer in Go that works for my particular use case.  [Here](https://github.com/acolytec3/gomobile_pss_signer) it is for reference if you want to see what I did.  I'll close this issue for now.
