### ISSUE TITLE
Incorrect use of flutter_lints dependency

### ISSUE THREAD

**Issue by SimoneBressan** [jerson/flutter-rsa#83]
Please move the `flutter_lints` dependency from `dependencies` to `dev_dependencies`
You should not force lints on people using the library

**Comment by jerson** [comment]
@SimoneBressan updated, thanks for report it I didn't realize I made the change in dependencies

**Comment by SimoneBressan** [comment]
@jerson  Thank you very much, I'm waiting for a release
